// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sqlx} from '../models';

export function DeleteNote(arg1:number):Promise<void>;

export function GetNote(arg1:number):Promise<models.Note>;

export function GetNotes():Promise<Array<models.Note>>;

export function SaveNote(arg1:models.Note):Promise<models.Note>;

export function Startup(arg1:context.Context,arg2:sqlx.DB):Promise<void>;
