// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['notes']['Service']['DeleteNote'](arg1);
}

export function GetNote(arg1) {
  return window['go']['notes']['Service']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['notes']['Service']['GetNotes']();
}

export function SaveNote(arg1) {
  return window['go']['notes']['Service']['SaveNote'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['notes']['Service']['Startup'](arg1, arg2);
}
