// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHttpPort() {
  return window['go']['services']['App']['GetHttpPort']();
}

export function SetHttpPort(arg1) {
  return window['go']['services']['App']['SetHttpPort'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['services']['App']['Startup'](arg1, arg2);
}
