// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {sqlx} from '../models';

export function GetHttpPort():Promise<number>;

export function SetHttpPort(arg1:any):Promise<void>;

export function Startup(arg1:context.Context,arg2:sqlx.DB):Promise<void>;
