name: Build Go Wails Application for macOS

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        brew install upx

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go dependencies
      run: go mod tidy

    - name: Install Wails CLI
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Build frontend assets
      shell: bash
      run: |
        npm install -g npm
        cd frontend
        npm install

    - name: Build Wails application for macOS
      run: wails build -clean

    - name: Archive macOS build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wails-build-macos
        path: build/bin/
